"""empty message

Revision ID: 3b2cd4088bbe
Revises: 41b3b5d48176
Create Date: 2020-07-16 15:15:22.231502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2cd4088bbe'
down_revision = '41b3b5d48176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website')
    op.drop_column('venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.VARCHAR(length=120), server_default=sa.text("'No Website'::character varying"), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('website', sa.VARCHAR(length=120), server_default=sa.text("'No Website'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
